
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import Datos.Archivo.TipoItemRegistro;
import java.util.*;
import java_cup.runtime.Symbol;
import Datos.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class analisis_sintacticos_datos extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return simbolos_datos.class;
}

  /** Default constructor. */
  @Deprecated
  public analisis_sintacticos_datos() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public analisis_sintacticos_datos(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public analisis_sintacticos_datos(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\013\000\002\002\004\000\002\003\003\000\002\013" +
    "\014\000\002\012\005\000\002\012\003\000\002\010\006" +
    "\000\002\010\005\000\002\011\005\000\002\011\003\000" +
    "\002\014\003\000\002\014\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\034\000\004\020\005\001\002\000\004\002\000\001" +
    "\002\000\004\014\010\001\002\000\004\002\007\001\002" +
    "\000\004\002\001\001\002\000\004\012\011\001\002\000" +
    "\006\016\013\017\014\001\002\000\006\006\ufffd\013\ufffd" +
    "\001\002\000\010\006\ufff7\011\ufff7\013\ufff7\001\002\000" +
    "\010\006\ufff8\011\ufff8\013\ufff8\001\002\000\006\006\016" +
    "\013\017\001\002\000\006\016\013\017\014\001\002\000" +
    "\004\021\020\001\002\000\004\014\021\001\002\000\004" +
    "\012\022\001\002\000\004\010\024\001\002\000\006\010" +
    "\032\013\033\001\002\000\006\016\013\017\014\001\002" +
    "\000\006\006\030\011\027\001\002\000\006\006\ufff9\011" +
    "\ufff9\001\002\000\006\010\ufffb\013\ufffb\001\002\000\006" +
    "\016\013\017\014\001\002\000\006\006\ufffa\011\ufffa\001" +
    "\002\000\006\016\013\017\014\001\002\000\004\002\uffff" +
    "\001\002\000\006\006\030\011\035\001\002\000\006\010" +
    "\ufffc\013\ufffc\001\002\000\006\006\ufffe\013\ufffe\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\034\000\006\003\005\013\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\012\014\014\011\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\014\035\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\010\022\001\001" +
    "\000\002\001\001\000\006\011\024\014\025\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\014\030\001\001\000\002\001\001\000\006\011\033\014" +
    "\025\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$analisis_sintacticos_datos$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$analisis_sintacticos_datos$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$analisis_sintacticos_datos$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  
    /*public static LinkedList<AcepErr> TablaErr=new LinkedList<AcepErr>();*/

    public Archivo resultado;
    //Metodo al que se llama automaticamente ante algun error sintactico
    public void syntax_error(Symbol s)
    {        
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;
        
        System.out.println("!!!!!!! Error Sintactico Recuperado !!!!!!!");
        System.out.println("\t\tLexema: "+lexema);
        System.out.println("\t\tFila: "+fila);
        System.out.println("\t\tColumna: "+columna);

        //lista_errores.add(new ErrorT(lexema, fila, columna,"sintactico" ,"Simbolo no esperado"));
        /*AcepErr datos =new AcepErr(lexema, "ERROR SINTACTICO" ,fila,columna,"Simbolo no esperado");
            TablaErr.add(datos);
            */
    }

    //Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {        
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;
        
        System.out.println("!!!!!!! Error Sintactico, Panic Mode !!!!!!! ");
        System.out.println("\t\tLexema: "+lexema);
        System.out.println("\t\tFila: "+fila);
        System.out.println("\t\tColumna: "+columna);

       /*AcepErr datos =new AcepErr(lexema, "ERROR SINTACTICO" ,fila,columna,"Simbolo no esperado Error Fatal");
                   TablaErr.add(datos);
                  */
        //lista_errores.add(new ErrorT(lexema, fila, columna,"sintactico" ,"Simbolo no esperado, Panic Mode"));
    }

    public void semantic(Symbol cur_token, String n) 
    {
        System.out.println("error semantico ");
    }

    public void semantic(String msg, Object obj) {}



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$analisis_sintacticos_datos$actions {


//METODOS Y VARIABLES QUE SOLO PUEDEN SER ACCEDIDAS DENTRO DEL PARSER
int exponente(int exp){
    int resultado= 1;
    for(int i=1; i<exp; i++){
        resultado = resultado *2;
    }
    return resultado;
}


  private final analisis_sintacticos_datos parser;

  /** Constructor */
  CUP$analisis_sintacticos_datos$actions(analisis_sintacticos_datos parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$analisis_sintacticos_datos$do_action_part00000000(
    int                        CUP$analisis_sintacticos_datos$act_num,
    java_cup.runtime.lr_parser CUP$analisis_sintacticos_datos$parser,
    java.util.Stack            CUP$analisis_sintacticos_datos$stack,
    int                        CUP$analisis_sintacticos_datos$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$analisis_sintacticos_datos$result;

      /* select the action based on the action number */
      switch (CUP$analisis_sintacticos_datos$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-1)).right;
		Archivo start_val = (Archivo)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-1)).value;
		RESULT = start_val;
              CUP$analisis_sintacticos_datos$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-1)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$analisis_sintacticos_datos$parser.done_parsing();
          return CUP$analisis_sintacticos_datos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= ARCHIVO 
            {
              Archivo RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).right;
		Archivo ls = (Archivo)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.peek()).value;
		
            parser.resultado = ls;
        
              CUP$analisis_sintacticos_datos$result = parser.getSymbolFactory().newSymbol("INICIO",1, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_datos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // ARCHIVO ::= claves igual acorch LISTACLAVES ccorch registros igual acorch LISTAREGISTROS ccorch 
            {
              Archivo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-6)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-6)).right;
		LinkedList<ItemRegistro> a = (LinkedList<ItemRegistro>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-6)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-1)).right;
		LinkedList<Registro> d = (LinkedList<Registro>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-1)).value;
		
                RESULT = new Archivo(a, d, aright, aleft);        
            
              CUP$analisis_sintacticos_datos$result = parser.getSymbolFactory().newSymbol("ARCHIVO",9, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-9)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_datos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LISTACLAVES ::= LISTACLAVES coma ITEM 
            {
              LinkedList<ItemRegistro> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-2)).right;
		LinkedList<ItemRegistro> a = (LinkedList<ItemRegistro>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).right;
		ItemRegistro b = (ItemRegistro)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.peek()).value;
		 
                RESULT = a;
                RESULT.add(b);
            
              CUP$analisis_sintacticos_datos$result = parser.getSymbolFactory().newSymbol("LISTACLAVES",8, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_datos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // LISTACLAVES ::= ITEM 
            {
              LinkedList<ItemRegistro> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).right;
		ItemRegistro a = (ItemRegistro)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.peek()).value;
		 
                RESULT = new LinkedList<>();
                RESULT.add(a);
            
              CUP$analisis_sintacticos_datos$result = parser.getSymbolFactory().newSymbol("LISTACLAVES",8, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_datos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // LISTAREGISTROS ::= LISTAREGISTROS allave LISTAITEM cllave 
            {
              LinkedList<Registro> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-3)).right;
		LinkedList<Registro> a = (LinkedList<Registro>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-1)).right;
		LinkedList<ItemRegistro> b = (LinkedList<ItemRegistro>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-1)).value;
		 
                    RESULT = a;
                    RESULT.add(new Registro(b, false, aright, aleft));
                 
              CUP$analisis_sintacticos_datos$result = parser.getSymbolFactory().newSymbol("LISTAREGISTROS",6, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-3)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_datos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // LISTAREGISTROS ::= allave LISTAITEM cllave 
            {
              LinkedList<Registro> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-1)).right;
		LinkedList<ItemRegistro> a = (LinkedList<ItemRegistro>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-1)).value;
		 
                    RESULT = new LinkedList<>();
                    RESULT.add(new Registro(a, true, aright, aleft)); 
                
              CUP$analisis_sintacticos_datos$result = parser.getSymbolFactory().newSymbol("LISTAREGISTROS",6, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_datos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // LISTAITEM ::= LISTAITEM coma ITEM 
            {
              LinkedList<ItemRegistro> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-2)).right;
		LinkedList<ItemRegistro> a = (LinkedList<ItemRegistro>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).right;
		ItemRegistro b = (ItemRegistro)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.peek()).value;
		 
                RESULT = a;
                RESULT.add(b);
           
              CUP$analisis_sintacticos_datos$result = parser.getSymbolFactory().newSymbol("LISTAITEM",7, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.elementAt(CUP$analisis_sintacticos_datos$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_datos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // LISTAITEM ::= ITEM 
            {
              LinkedList<ItemRegistro> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).right;
		ItemRegistro a = (ItemRegistro)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.peek()).value;
		 
                RESULT = new LinkedList<>();
                RESULT.add(a);
            
              CUP$analisis_sintacticos_datos$result = parser.getSymbolFactory().newSymbol("LISTAITEM",7, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_datos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // ITEM ::= cadena 
            {
              ItemRegistro RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.peek()).value;
		 RESULT = new ItemRegistro(TipoItemRegistro.CADENA, a, aright, aleft); 
              CUP$analisis_sintacticos_datos$result = parser.getSymbolFactory().newSymbol("ITEM",10, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_datos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // ITEM ::= numero 
            {
              ItemRegistro RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_datos$stack.peek()).value;
		 RESULT = new ItemRegistro(TipoItemRegistro.NUMERO, a, aright, aleft); 
              CUP$analisis_sintacticos_datos$result = parser.getSymbolFactory().newSymbol("ITEM",10, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_datos$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_datos$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$analisis_sintacticos_datos$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$analisis_sintacticos_datos$do_action(
    int                        CUP$analisis_sintacticos_datos$act_num,
    java_cup.runtime.lr_parser CUP$analisis_sintacticos_datos$parser,
    java.util.Stack            CUP$analisis_sintacticos_datos$stack,
    int                        CUP$analisis_sintacticos_datos$top)
    throws java.lang.Exception
    {
              return CUP$analisis_sintacticos_datos$do_action_part00000000(
                               CUP$analisis_sintacticos_datos$act_num,
                               CUP$analisis_sintacticos_datos$parser,
                               CUP$analisis_sintacticos_datos$stack,
                               CUP$analisis_sintacticos_datos$top);
    }
}

}
