
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import java.awt.TextArea;
import java.util.*;
import java_cup.runtime.Symbol;
import Entorno.*;
import Entorno.Simbolo.EnumTipoDato;
import Expresion.*;
import Instruccion.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class analisis_sintacticos_re extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Simbolos.class;
}

  /** Default constructor. */
  @Deprecated
  public analisis_sintacticos_re() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public analisis_sintacticos_re(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public analisis_sintacticos_re(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\020\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\006\003\000\002\006\003" +
    "\000\002\006\004\000\002\005\007\000\002\010\003\000" +
    "\002\010\003\000\002\004\007\000\002\007\006\000\002" +
    "\007\006\000\002\007\003\000\002\007\003\000\002\007" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\041\000\012\003\012\023\010\024\006\025\013\001" +
    "\002\000\014\002\ufffe\003\ufffe\023\ufffe\024\ufffe\025\ufffe" +
    "\001\002\000\014\002\ufffd\003\ufffd\023\ufffd\024\ufffd\025" +
    "\ufffd\001\002\000\004\015\ufff9\001\002\000\004\002\043" +
    "\001\002\000\004\004\037\001\002\000\004\015\020\001" +
    "\002\000\004\007\017\001\002\000\004\015\ufff8\001\002" +
    "\000\014\002\ufffc\003\ufffc\023\ufffc\024\ufffc\025\ufffc\001" +
    "\002\000\014\002\000\003\012\023\010\024\006\025\013" +
    "\001\002\000\014\002\uffff\003\uffff\023\uffff\024\uffff\025" +
    "\uffff\001\002\000\014\002\ufffb\003\ufffb\023\ufffb\024\ufffb" +
    "\025\ufffb\001\002\000\004\010\021\001\002\000\014\015" +
    "\027\016\022\017\023\022\026\026\024\001\002\000\006" +
    "\005\ufff4\007\ufff4\001\002\000\006\005\ufff3\007\ufff3\001" +
    "\002\000\004\004\034\001\002\000\004\007\033\001\002" +
    "\000\004\004\030\001\002\000\006\005\ufff2\007\ufff2\001" +
    "\002\000\014\015\027\016\022\017\023\022\026\026\024" +
    "\001\002\000\004\005\032\001\002\000\006\005\ufff5\007" +
    "\ufff5\001\002\000\014\002\ufffa\003\ufffa\023\ufffa\024\ufffa" +
    "\025\ufffa\001\002\000\014\015\027\016\022\017\023\022" +
    "\026\026\024\001\002\000\004\005\036\001\002\000\006" +
    "\005\ufff6\007\ufff6\001\002\000\014\015\027\016\022\017" +
    "\023\022\026\026\024\001\002\000\004\005\041\001\002" +
    "\000\004\007\042\001\002\000\014\002\ufff7\003\ufff7\023" +
    "\ufff7\024\ufff7\025\ufff7\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\041\000\016\002\006\003\014\004\013\005\004\006" +
    "\003\010\010\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\004\013\005\004\006\015\010\010\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\007\024\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\007\030\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\007\034" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\007" +
    "\037\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$analisis_sintacticos_re$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$analisis_sintacticos_re$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$analisis_sintacticos_re$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  
    /*public static LinkedList<AcepErr> TablaErr=new LinkedList<AcepErr>();*/

    public LinkedList<Instruccion> resultado = new LinkedList<>();
    public TextArea salidaConsola;

    //Metodo al que se llama automaticamente ante algun error sintactico
    public void syntax_error(Symbol s)
    {        
        String lexema = s.value.toString();
        int fila = s.right + 1;
        int columna = s.left + 1;
        
        String info = "!!!!!!! Error Sintactico Recuperado !!!!!!!\n"+
                      "\tLexema: "+lexema+
                      "\tFila: "+fila+
                      "\tColumna: "+columna+
                      "\n";

        salidaConsola.append(info);
        //lista_errores.add(new ErrorT(lexema, fila, columna,"sintactico" ,"Simbolo no esperado"));
        /*AcepErr datos =new AcepErr(lexema, "ERROR SINTACTICO" ,fila,columna,"Simbolo no esperado");
            TablaErr.add(datos);
            */
    }

    //Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {        
        String lexema = s.value.toString();
        int fila = s.right + 1;
        int columna = s.left + 1;
        
        String info = "!!!!!!! Error Sintactico, Panic Mode !!!!!!! "+
                "\tLexema: "+lexema+
                "\tFila: "+fila+
                "\tColumna: "+columna+
                "\n";

       /*AcepErr datos =new AcepErr(lexema, "ERROR SINTACTICO" ,fila,columna,"Simbolo no esperado Error Fatal");
                   TablaErr.add(datos);
                  */
        //lista_errores.add(new ErrorT(lexema, fila, columna,"sintactico" ,"Simbolo no esperado, Panic Mode"));
    }

    public void semantic(Symbol cur_token, String n) 
    {
        System.out.println("error semantico ");
    }

    public void semantic(String msg, Object obj) {}



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$analisis_sintacticos_re$actions {




  private final analisis_sintacticos_re parser;

  /** Constructor */
  CUP$analisis_sintacticos_re$actions(analisis_sintacticos_re parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$analisis_sintacticos_re$do_action_part00000000(
    int                        CUP$analisis_sintacticos_re$act_num,
    java_cup.runtime.lr_parser CUP$analisis_sintacticos_re$parser,
    java.util.Stack            CUP$analisis_sintacticos_re$stack,
    int                        CUP$analisis_sintacticos_re$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$analisis_sintacticos_re$result;

      /* select the action based on the action number */
      switch (CUP$analisis_sintacticos_re$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		LinkedList<Instruccion> start_val = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		RESULT = start_val;
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$analisis_sintacticos_re$parser.done_parsing();
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= LISTAINSTRUCCION 
            {
              LinkedList<Instruccion> RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		LinkedList<Instruccion> ls = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		
            parser.resultado = ls;
        
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // LISTAINSTRUCCION ::= LISTAINSTRUCCION INSTRUCCION 
            {
              LinkedList<Instruccion> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		LinkedList<Instruccion> a = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		Instruccion b = (Instruccion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		
                    RESULT = a;
                    RESULT.add(b);
                
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("LISTAINSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LISTAINSTRUCCION ::= INSTRUCCION 
            {
              LinkedList<Instruccion> RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		Instruccion b = (Instruccion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		
                    RESULT = new LinkedList<>(); 
                    RESULT.add(b);
                
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("LISTAINSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INSTRUCCION ::= DECLARACION 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		Instruccion a = (Instruccion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = a; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",4, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // INSTRUCCION ::= IMPRIMIR 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		Instruccion a = (Instruccion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = a; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",4, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // INSTRUCCION ::= error puntoComa 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		 RESULT = new InstruccionConError("Existe una instrucción con error, No se reconoció correctamente", aright, aleft); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",4, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // DECLARACION ::= TIPO id igual E puntoComa 
            {
              Instruccion RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).right;
		EnumTipoDato tipo = (EnumTipoDato)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).value;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).value;
		int asignacionleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int asignacionright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		Expresion asignacion = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		 RESULT = new Declaracion(tipo, nombre, asignacion, tiporight, tipoleft); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // TIPO ::= numerico 
            {
              EnumTipoDato RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = EnumTipoDato.NUMERICO; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("TIPO",6, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // TIPO ::= archivo 
            {
              EnumTipoDato RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = EnumTipoDato.ARCHIVO; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("TIPO",6, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // IMPRIMIR ::= imprimir apar E cpar puntoComa 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-2)).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-2)).value;
		 RESULT = new Imprimir(b, aright, aleft); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("IMPRIMIR",2, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // E ::= leerarchivo apar E cpar 
            {
              Expresion RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).value;
		int rutaleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int rutaright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		Expresion ruta = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		 RESULT = new FuncionLeerArchivo(ruta, lright, lleft); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("E",5, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // E ::= contar apar E cpar 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		 RESULT = new Contar(b); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("E",5, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // E ::= numero 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = new Literal(EnumTipoDato.NUMERICO, a); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("E",5, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // E ::= cadena 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = new Literal(EnumTipoDato.CADENA, a); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("E",5, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // E ::= id 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = new Id(a, aright, aleft); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("E",5, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$analisis_sintacticos_re$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$analisis_sintacticos_re$do_action(
    int                        CUP$analisis_sintacticos_re$act_num,
    java_cup.runtime.lr_parser CUP$analisis_sintacticos_re$parser,
    java.util.Stack            CUP$analisis_sintacticos_re$stack,
    int                        CUP$analisis_sintacticos_re$top)
    throws java.lang.Exception
    {
              return CUP$analisis_sintacticos_re$do_action_part00000000(
                               CUP$analisis_sintacticos_re$act_num,
                               CUP$analisis_sintacticos_re$parser,
                               CUP$analisis_sintacticos_re$stack,
                               CUP$analisis_sintacticos_re$top);
    }
}

}
