
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import Datos.Archivo.TipoRelacional;
import java.awt.TextArea;
import java.util.*;
import java_cup.runtime.Symbol;
import Entorno.*;
import Entorno.Simbolo.EnumTipoDato;
import Expresion.*;
import Instruccion.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class analisis_sintacticos_re extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Simbolos.class;
}

  /** Default constructor. */
  @Deprecated
  public analisis_sintacticos_re() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public analisis_sintacticos_re(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public analisis_sintacticos_re(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\034\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\007\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\004\000\002\006\007\000" +
    "\002\012\003\000\002\012\003\000\002\010\017\000\002" +
    "\005\007\000\002\004\005\000\002\004\003\000\002\011" +
    "\006\000\002\011\006\000\002\011\014\000\002\011\010" +
    "\000\002\011\003\000\002\011\003\000\002\011\003\000" +
    "\002\013\003\000\002\013\003\000\002\013\003\000\002" +
    "\013\003\000\002\013\003\000\002\013\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\110\000\014\003\012\033\010\034\006\035\013\037" +
    "\014\001\002\000\016\002\ufffe\003\ufffe\033\ufffe\034\ufffe" +
    "\035\ufffe\037\ufffe\001\002\000\016\002\ufffd\003\ufffd\033" +
    "\ufffd\034\ufffd\035\ufffd\037\ufffd\001\002\000\004\023\ufff8" +
    "\001\002\000\004\002\112\001\002\000\004\004\103\001" +
    "\002\000\004\023\077\001\002\000\004\007\076\001\002" +
    "\000\004\023\ufff7\001\002\000\004\004\021\001\002\000" +
    "\016\002\ufffc\003\ufffc\033\ufffc\034\ufffc\035\ufffc\037\ufffc" +
    "\001\002\000\016\002\ufffb\003\ufffb\033\ufffb\034\ufffb\035" +
    "\ufffb\037\ufffb\001\002\000\016\002\000\003\012\033\010" +
    "\034\006\035\013\037\014\001\002\000\016\002\uffff\003" +
    "\uffff\033\uffff\034\uffff\035\uffff\037\uffff\001\002\000\020" +
    "\023\031\024\023\025\024\030\030\031\025\032\022\036" +
    "\026\001\002\000\004\004\057\001\002\000\010\005\uffee" +
    "\006\uffee\007\uffee\001\002\000\010\005\uffed\006\uffed\007" +
    "\uffed\001\002\000\004\004\052\001\002\000\004\004\047" +
    "\001\002\000\004\006\035\001\002\000\004\004\032\001" +
    "\002\000\010\005\uffec\006\uffec\007\uffec\001\002\000\020" +
    "\023\031\024\023\025\024\030\030\031\025\032\022\036" +
    "\026\001\002\000\004\005\034\001\002\000\010\005\ufff1" +
    "\006\ufff1\007\ufff1\001\002\000\020\023\031\024\023\025" +
    "\024\030\030\031\025\032\022\036\026\001\002\000\004" +
    "\006\037\001\002\000\020\023\031\024\023\025\024\030" +
    "\030\031\025\032\022\036\026\001\002\000\004\006\041" +
    "\001\002\000\020\023\031\024\023\025\024\030\030\031" +
    "\025\032\022\036\026\001\002\000\004\006\043\001\002" +
    "\000\020\023\031\024\023\025\024\030\030\031\025\032" +
    "\022\036\026\001\002\000\004\005\045\001\002\000\004" +
    "\007\046\001\002\000\016\002\ufff6\003\ufff6\033\ufff6\034" +
    "\ufff6\035\ufff6\037\ufff6\001\002\000\020\023\031\024\023" +
    "\025\024\030\030\031\025\032\022\036\026\001\002\000" +
    "\004\005\051\001\002\000\010\005\ufff2\006\ufff2\007\ufff2" +
    "\001\002\000\020\023\031\024\023\025\024\030\030\031" +
    "\025\032\022\036\026\001\002\000\004\006\054\001\002" +
    "\000\020\023\031\024\023\025\024\030\030\031\025\032" +
    "\022\036\026\001\002\000\004\005\056\001\002\000\010" +
    "\005\uffef\006\uffef\007\uffef\001\002\000\020\023\031\024" +
    "\023\025\024\030\030\031\025\032\022\036\026\001\002" +
    "\000\004\006\061\001\002\000\020\023\031\024\023\025" +
    "\024\030\030\031\025\032\022\036\026\001\002\000\004" +
    "\006\063\001\002\000\016\011\064\012\071\013\067\014" +
    "\070\015\072\016\066\001\002\000\004\006\uffeb\001\002" +
    "\000\004\006\073\001\002\000\004\006\uffe6\001\002\000" +
    "\004\006\uffe9\001\002\000\004\006\uffe8\001\002\000\004" +
    "\006\uffea\001\002\000\004\006\uffe7\001\002\000\020\023" +
    "\031\024\023\025\024\030\030\031\025\032\022\036\026" +
    "\001\002\000\004\005\075\001\002\000\010\005\ufff0\006" +
    "\ufff0\007\ufff0\001\002\000\016\002\ufffa\003\ufffa\033\ufffa" +
    "\034\ufffa\035\ufffa\037\ufffa\001\002\000\004\010\100\001" +
    "\002\000\020\023\031\024\023\025\024\030\030\031\025" +
    "\032\022\036\026\001\002\000\004\007\102\001\002\000" +
    "\016\002\ufff9\003\ufff9\033\ufff9\034\ufff9\035\ufff9\037\ufff9" +
    "\001\002\000\020\023\031\024\023\025\024\030\030\031" +
    "\025\032\022\036\026\001\002\000\006\005\106\006\107" +
    "\001\002\000\006\005\ufff3\006\ufff3\001\002\000\004\007" +
    "\111\001\002\000\020\023\031\024\023\025\024\030\030" +
    "\031\025\032\022\036\026\001\002\000\006\005\ufff4\006" +
    "\ufff4\001\002\000\016\002\ufff5\003\ufff5\033\ufff5\034\ufff5" +
    "\035\ufff5\037\ufff5\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\110\000\020\002\006\003\016\005\014\006\004\007" +
    "\003\010\015\012\010\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\005\014\006\004\007\017\010\015\012\010\001\001" +
    "\000\002\001\001\000\004\011\026\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\011\032\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\035\001\001\000\002\001" +
    "\001\000\004\011\037\001\001\000\002\001\001\000\004" +
    "\011\041\001\001\000\002\001\001\000\004\011\043\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\011\047\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\011\052\001\001\000\002\001\001\000\004" +
    "\011\054\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\011\057\001\001\000\002\001\001\000\004\011\061" +
    "\001\001\000\002\001\001\000\004\013\064\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\011\073\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\100\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\004\103\011\104\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\011\107\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$analisis_sintacticos_re$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$analisis_sintacticos_re$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$analisis_sintacticos_re$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  
    /*public static LinkedList<AcepErr> TablaErr=new LinkedList<AcepErr>();*/

    public LinkedList<Instruccion> resultado = new LinkedList<>();
    public TextArea salidaConsola;

    //Metodo al que se llama automaticamente ante algun error sintactico
    public void syntax_error(Symbol s)
    {        
        String lexema = s.value.toString();
        int fila = s.right + 1;
        int columna = s.left + 1;
        
        String info = "!!!!!!! Error Sintactico Recuperado !!!!!!!\n"+
                      "\tLexema: "+lexema+
                      "\tFila: "+fila+
                      "\tColumna: "+columna+
                      "\n";

        salidaConsola.append(info);
        //lista_errores.add(new ErrorT(lexema, fila, columna,"sintactico" ,"Simbolo no esperado"));
        /*AcepErr datos =new AcepErr(lexema, "ERROR SINTACTICO" ,fila,columna,"Simbolo no esperado");
            TablaErr.add(datos);
            */
    }

    //Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {        
        String lexema = s.value.toString();
        int fila = s.right + 1;
        int columna = s.left + 1;
        
        String info = "!!!!!!! Error Sintactico, Panic Mode !!!!!!! "+
                "\tLexema: "+lexema+
                "\tFila: "+fila+
                "\tColumna: "+columna+
                "\n";

       /*AcepErr datos =new AcepErr(lexema, "ERROR SINTACTICO" ,fila,columna,"Simbolo no esperado Error Fatal");
                   TablaErr.add(datos);
                  */
        //lista_errores.add(new ErrorT(lexema, fila, columna,"sintactico" ,"Simbolo no esperado, Panic Mode"));
    }

    public void semantic(Symbol cur_token, String n) 
    {
        System.out.println("error semantico ");
    }

    public void semantic(String msg, Object obj) {}



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$analisis_sintacticos_re$actions {




  private final analisis_sintacticos_re parser;

  /** Constructor */
  CUP$analisis_sintacticos_re$actions(analisis_sintacticos_re parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$analisis_sintacticos_re$do_action_part00000000(
    int                        CUP$analisis_sintacticos_re$act_num,
    java_cup.runtime.lr_parser CUP$analisis_sintacticos_re$parser,
    java.util.Stack            CUP$analisis_sintacticos_re$stack,
    int                        CUP$analisis_sintacticos_re$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$analisis_sintacticos_re$result;

      /* select the action based on the action number */
      switch (CUP$analisis_sintacticos_re$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		LinkedList<Instruccion> start_val = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		RESULT = start_val;
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$analisis_sintacticos_re$parser.done_parsing();
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= LISTAINSTRUCCION 
            {
              LinkedList<Instruccion> RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		LinkedList<Instruccion> ls = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		
            parser.resultado = ls;
        
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // LISTAINSTRUCCION ::= LISTAINSTRUCCION INSTRUCCION 
            {
              LinkedList<Instruccion> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		LinkedList<Instruccion> a = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		Instruccion b = (Instruccion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		
                    RESULT = a;
                    RESULT.add(b);
                
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("LISTAINSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LISTAINSTRUCCION ::= INSTRUCCION 
            {
              LinkedList<Instruccion> RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		Instruccion b = (Instruccion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		
                    RESULT = new LinkedList<>(); 
                    RESULT.add(b);
                
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("LISTAINSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INSTRUCCION ::= DECLARACION 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		Instruccion a = (Instruccion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = a; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",5, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // INSTRUCCION ::= IMPRIMIR 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		Instruccion a = (Instruccion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = a; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",5, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // INSTRUCCION ::= GRAFICAR 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		Instruccion a = (Instruccion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = a; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",5, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // INSTRUCCION ::= error puntoComa 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		 RESULT = new InstruccionConError("Existe una instrucción con error, No se reconoció correctamente", aright, aleft); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",5, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // DECLARACION ::= TIPO id igual E puntoComa 
            {
              Instruccion RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).right;
		EnumTipoDato tipo = (EnumTipoDato)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).value;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).value;
		int asignacionleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int asignacionright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		Expresion asignacion = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		 RESULT = new Declaracion(tipo, nombre, asignacion, tiporight, tipoleft); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("DECLARACION",4, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // TIPO ::= numerico 
            {
              EnumTipoDato RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = EnumTipoDato.NUMERICO; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("TIPO",8, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // TIPO ::= archivo 
            {
              EnumTipoDato RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = EnumTipoDato.ARCHIVO; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("TIPO",8, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // GRAFICAR ::= graficar apar E coma E coma E coma E coma E cpar puntoComa 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-12)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-12)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-12)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-10)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-10)).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-10)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-8)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-8)).right;
		Expresion c = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-8)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-6)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-6)).right;
		Expresion d = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-6)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).right;
		Expresion r = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-2)).right;
		Expresion f = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-2)).value;
		 RESULT = new Graficar(b, c, d, r, f, aright, aleft); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("GRAFICAR",6, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-12)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // IMPRIMIR ::= imprimir apar LISTAE cpar puntoComa 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-2)).right;
		LinkedList<Expresion> b = (LinkedList<Expresion>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-2)).value;
		 RESULT = new Imprimir(b, aright, aleft); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("IMPRIMIR",3, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-4)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // LISTAE ::= LISTAE coma E 
            {
              LinkedList<Expresion> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-2)).right;
		LinkedList<Expresion> l = (LinkedList<Expresion>)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		
            RESULT = l;
            l.add(a);
        
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("LISTAE",2, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // LISTAE ::= E 
            {
              LinkedList<Expresion> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		
            RESULT = new LinkedList<>();
            RESULT.add(a);
        
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("LISTAE",2, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // E ::= leerarchivo apar E cpar 
            {
              Expresion RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).value;
		int rutaleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int rutaright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		Expresion ruta = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		 RESULT = new FuncionLeerArchivo(ruta, lright, lleft); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // E ::= contar apar E cpar 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		 RESULT = new Contar(b); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // E ::= contarSi apar E coma E coma RELA coma E cpar 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-9)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-9)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-9)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-7)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-7)).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-7)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-5)).right;
		Expresion c = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-5)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).right;
		TipoRelacional d = (TipoRelacional)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		Expresion val = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		 RESULT = new ContarSi(b, c, d, val, aright, aleft); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-9)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // E ::= sumar apar E coma E cpar 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-5)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-5)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-5)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).right;
		Expresion c = (Expresion)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-1)).value;
		 RESULT = new Sumar(b, c, aright, aleft); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.elementAt(CUP$analisis_sintacticos_re$top-5)), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // E ::= numero 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = new Literal(EnumTipoDato.NUMERICO, a); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // E ::= cadena 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = new Literal(EnumTipoDato.CADENA, a); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // E ::= id 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$analisis_sintacticos_re$stack.peek()).value;
		 RESULT = new Id(a, aright, aleft); 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // RELA ::= igualigual 
            {
              TipoRelacional RESULT =null;
		 RESULT = TipoRelacional.IGUALIGUAL; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("RELA",9, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // RELA ::= mayor 
            {
              TipoRelacional RESULT =null;
		 RESULT = TipoRelacional.MAYOR; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("RELA",9, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // RELA ::= menor 
            {
              TipoRelacional RESULT =null;
		 RESULT = TipoRelacional.MENOR; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("RELA",9, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // RELA ::= mayorigual 
            {
              TipoRelacional RESULT =null;
		 RESULT = TipoRelacional.MAYORIGUAL; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("RELA",9, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // RELA ::= menorigual 
            {
              TipoRelacional RESULT =null;
		 RESULT = TipoRelacional.MENORIGUAL; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("RELA",9, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // RELA ::= diferenteque 
            {
              TipoRelacional RESULT =null;
		 RESULT = TipoRelacional.DIFERENTEQUE; 
              CUP$analisis_sintacticos_re$result = parser.getSymbolFactory().newSymbol("RELA",9, ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintacticos_re$stack.peek()), RESULT);
            }
          return CUP$analisis_sintacticos_re$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$analisis_sintacticos_re$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$analisis_sintacticos_re$do_action(
    int                        CUP$analisis_sintacticos_re$act_num,
    java_cup.runtime.lr_parser CUP$analisis_sintacticos_re$parser,
    java.util.Stack            CUP$analisis_sintacticos_re$stack,
    int                        CUP$analisis_sintacticos_re$top)
    throws java.lang.Exception
    {
              return CUP$analisis_sintacticos_re$do_action_part00000000(
                               CUP$analisis_sintacticos_re$act_num,
                               CUP$analisis_sintacticos_re$parser,
                               CUP$analisis_sintacticos_re$stack,
                               CUP$analisis_sintacticos_re$top);
    }
}

}
