
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int menorigual = 11;
  public static final int registros = 22;
  public static final int cadena = 20;
  public static final int promedio = 13;
  public static final int coma = 4;
  public static final int archivo = 29;
  public static final int numero = 19;
  public static final int imprimir = 27;
  public static final int leerarchivo = 30;
  public static final int sumar = 24;
  public static final int cpar = 3;
  public static final int por = 16;
  public static final int contarSi = 25;
  public static final int claves = 21;
  public static final int numerico = 28;
  public static final int menos = 15;
  public static final int menor = 9;
  public static final int mayorigual = 10;
  public static final int igual = 6;
  public static final int EOF = 0;
  public static final int id = 18;
  public static final int obtenerSi = 26;
  public static final int contar = 23;
  public static final int error = 1;
  public static final int graficar = 31;
  public static final int mas = 14;
  public static final int puntoComa = 5;
  public static final int diferenteque = 12;
  public static final int igualigual = 7;
  public static final int dividir = 17;
  public static final int mayor = 8;
  public static final int apar = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "apar",
  "cpar",
  "coma",
  "puntoComa",
  "igual",
  "igualigual",
  "mayor",
  "menor",
  "mayorigual",
  "menorigual",
  "diferenteque",
  "promedio",
  "mas",
  "menos",
  "por",
  "dividir",
  "id",
  "numero",
  "cadena",
  "claves",
  "registros",
  "contar",
  "sumar",
  "contarSi",
  "obtenerSi",
  "imprimir",
  "numerico",
  "archivo",
  "leerarchivo",
  "graficar"
  };
}

