
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int cadena = 13;
  public static final int registros = 15;
  public static final int coma = 4;
  public static final int archivo = 20;
  public static final int numero = 12;
  public static final int imprimir = 18;
  public static final int leerarchivo = 21;
  public static final int sumar = 17;
  public static final int cpar = 3;
  public static final int por = 9;
  public static final int claves = 14;
  public static final int numerico = 19;
  public static final int menos = 8;
  public static final int igual = 6;
  public static final int EOF = 0;
  public static final int id = 11;
  public static final int error = 1;
  public static final int contar = 16;
  public static final int graficar = 22;
  public static final int mas = 7;
  public static final int puntoComa = 5;
  public static final int dividir = 10;
  public static final int apar = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "apar",
  "cpar",
  "coma",
  "puntoComa",
  "igual",
  "mas",
  "menos",
  "por",
  "dividir",
  "id",
  "numero",
  "cadena",
  "claves",
  "registros",
  "contar",
  "sumar",
  "imprimir",
  "numerico",
  "archivo",
  "leerarchivo",
  "graficar"
  };
}

