
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class simbolos_datos {
  /* terminals */
  public static final int acorch = 8;
  public static final int id = 11;
  public static final int coma = 4;
  public static final int claves = 14;
  public static final int registros = 15;
  public static final int cadena = 13;
  public static final int apar = 2;
  public static final int EOF = 0;
  public static final int cllave = 7;
  public static final int puntoComa = 5;
  public static final int numero = 12;
  public static final int ccorch = 9;
  public static final int error = 1;
  public static final int cpar = 3;
  public static final int allave = 6;
  public static final int igual = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "apar",
  "cpar",
  "coma",
  "puntoComa",
  "allave",
  "cllave",
  "acorch",
  "ccorch",
  "igual",
  "id",
  "numero",
  "cadena",
  "claves",
  "registros"
  };
}

