/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Analizadores.a_Lexico_rep;
import Analizadores.analisis_sintacticos_re;
import Entorno.Entorno;
import Instruccion.Declaracion;
import Instruccion.Instruccion;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.StringReader;
import java.util.LinkedList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author EG
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLayout(null);
    }
    private int cont=0;
    JTextArea tex1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        salidaConsola = new java.awt.TextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        idAbrir = new javax.swing.JMenu();
        idGuardar = new javax.swing.JMenu();
        idGuardarComo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Analizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        idAbrir.setText("Abrir");
        idAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idAbrirMouseClicked(evt);
            }
        });
        idAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAbrirActionPerformed(evt);
            }
        });
        jMenuBar1.add(idAbrir);

        idGuardar.setText("Guardar");
        idGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idGuardarActionPerformed(evt);
            }
        });
        jMenuBar1.add(idGuardar);

        idGuardarComo.setText("Guardar Como");
        idGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idGuardarComoActionPerformed(evt);
            }
        });
        jMenuBar1.add(idGuardarComo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salidaConsola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salidaConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Component comp = jTabbedPane1.getComponentAt(jTabbedPane1.getSelectedIndex());
        tex1=(JTextArea) comp;
        String datos = tex1.getText();
        analizarEntrada(datos);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void analizarEntrada(String datos){
        String entrada = datos;
        salidaConsola.setText("");
        a_Lexico_rep lexico = new a_Lexico_rep(new BufferedReader(new StringReader(entrada)));
        lexico.salidaConsola = salidaConsola;
        
        analisis_sintacticos_re sintactico = new analisis_sintacticos_re(lexico);
        sintactico.salidaConsola = salidaConsola;
        try{
            sintactico.parse();
            recorrerArbol(sintactico);
        }catch(Exception e){
            System.out.println(e);
        }
    }
     public void recorrerArbol(analisis_sintacticos_re sintactico){
        Entorno ent = new Entorno(null);
        Declaracion decl;
        LinkedList<Instruccion> listaInstrucciones = sintactico.resultado;
        for (Instruccion i : listaInstrucciones) {
            if(i!=null)
                i.ejecutar(ent);
        }
    }
    private void idAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAbrirActionPerformed
        
    }//GEN-LAST:event_idAbrirActionPerformed

    private void idGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idGuardarActionPerformed
         JOptionPane.showMessageDialog(null, "Hola Mundo");
    }//GEN-LAST:event_idGuardarActionPerformed

    private void idGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idGuardarComoActionPerformed
        JOptionPane.showMessageDialog(null, "Hola Mundo");
    }//GEN-LAST:event_idGuardarComoActionPerformed

    private void idAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idAbrirMouseClicked
         JFileChooser chooser = new JFileChooser();
         FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & GIF Images", "jpg", "gif");
          chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
         if(returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: " +
                    chooser.getSelectedFile().getName());
        }
        tex1 = new JTextArea();
        jTabbedPane1.addTab("Archivo"+(cont+1), tex1);
        cont++;
    }//GEN-LAST:event_idAbrirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu idAbrir;
    private javax.swing.JMenu idGuardar;
    private javax.swing.JMenu idGuardarComo;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static java.awt.TextArea salidaConsola;
    // End of variables declaration//GEN-END:variables
   
}
